---
title: |
  <center> University of Edinburgh, School of Mathematics </center>
  <center> Incomplete Data Analysis, 2020/2021 </center>
  <center> IDA assignment2
author: "Zeming Liang"
date: "2020/11/21"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include = TRUE, message = FALSE}
require(maxLik)
load("C:/Users/DELL/Desktop/IDA/assignment/IDA Assignment 2-Zeming_Liang/dataex2.Rdata")
load("C:/Users/DELL/Desktop/IDA/assignment/IDA Assignment 2-Zeming_Liang/dataex4.Rdata")
load("C:/Users/DELL/Desktop/IDA/assignment/IDA Assignment 2-Zeming_Liang/dataex5.Rdata")
```

```{r q2}
log_like_norm <- function(ob, mu){
  x = ob[,1]
  r = ob[2]
  sum(r*dnorm(x, mean=mu, sd=1.5, log=TRUE) + 
        (1-r)*pnorm(x, mean=mu, sd=1.5, lower.tail = TRUE, log.p = TRUE))
}
mle = maxLik(logLik = log_like_norm, ob = dataex2, start = 0)
summary(mle)
```


```{r q2 check}
normopt <- optim(par = 0, fn = log_like_norm, ob = dataex2, 
                 control = list("fnscale"=-1), hessian = TRUE)
normopt
sqrt(solve(-normopt$hessian))
```


```{r q4}
EM <- function(data, th0, eps){
  diff <- 1
  beta_old = th0

  while(diff>eps){
    beta0_old = beta_old[1]
    beta1_old = beta_old[2]
    #E-step
    E_step <- function(param, data){
      x <- data[,1]; y <- data[,2]; r <- ifelse(is.na(y), 0, 1)
      beta0 <- param[1]
      beta1 <- param[2]  
      Q1 = sum(y[r==1]*(beta0+beta1*x[r==1]))
      Q2 = -sum(log(1+exp(beta0+beta1*x)))
      Q3 = sum((beta0+beta1*x[r==0])*exp(beta0_old+beta1_old*x[r==0])/(1+exp(beta0_old+beta1_old*x[r==0])))
      Q1 + Q2 + Q3
    }   
    #M-step
    beta = coef(maxLik(E_step, data=data, start = beta_old))
    diff = max(abs(beta-beta_old))
    beta_old = beta
  }
  beta
}


EM(dataex4,c(0,0),10^(-14))

```




```{r q5 function}
em.mixture <- function(y, theta0, eps){
  n <- length(y)
  log_y = log(y)
  theta <- theta0

  p <- theta[1]; mu <- theta[2]; sigma2 <- theta[3]; lambda <- theta[4]

  diff <- 1
  while(diff > eps){
    theta.old <- theta

    #E-step
    ptilde1 <- p*dlnorm(y, mu, sqrt(sigma2))
    ptilde2 <- (1 - p)*dexp(y, rate = lambda)
    ptilde <- ptilde1/(ptilde1 + ptilde2)

    #M-step
    p <- mean(ptilde)

    mu <- sum(log_y*ptilde)/sum(ptilde)
    sigma2 <- sum(((log_y - mu)^2)*ptilde)/sum(ptilde)
    lambda <- sum(1 - ptilde)/sum(y*(1 - ptilde))

    theta <- data.frame(p, mu, sigma2, lambda)
    diff <- sum(abs(theta - theta.old))
  }
  return(theta)
}


```

```{r q5 application}
res <- em.mixture(y = dataex5, c(0.1, 1, 0.5^2, 2), 10^(-14))
res
```



```{r q5 plot}
hist(dataex5, breaks = 50, 
     xlab = "y",    
     main="Mixture Distribution of Norm and Exp",
     ylim= c(0,0.25),
     col= "lightblue",
     freq = FALSE)
attach(res)
curve(p*dlnorm(x, mu, sqrt(sigma2)) + (1-p)*dexp(x, lambda),
      add= TRUE, lwd = 2, col= "red")
legend("topright", 
       c("Histogram Data", "Mixed Distribution density"),
       fill=c("lightblue", "red"), cex = 0.75)
detach(res)
```